general:
  project: "example-com"
  env-short: "dev"
  regions:
    - eu-west-1

default-exposed-ports: &default-exposed-ports
  traefik-nodeport:
    number: 30443
    protocol: tcp
    cidr-filters:
      - 0.0.0.0/0

default-helm-charts: &default-helm-charts
  traefik:
    repository: https://traefik.github.io/charts
    version: 23.0.1
    namespace: kube-system
    valuesSet:
      deployment.kind: "DaemonSet"
      ports.websecure.nodePort: "30443"
      ports.web.exposed: "false"
      ports.websecure.exposed: "false"
      service.type: "NodePort"
#  aws-load-balancer-controller:
#    repository: https://aws.github.io/eks-charts
#    version: 1.5.2
#    namespace: kube-system
#    valuesYAMLTemplate:
#      clusterName: "$${clusterName}"

default-eks-addons: &default-eks-addons
  aws-ebs-csi-driver:
    addon-version: v1.18.0-eksbuild.1
    resolve-conflicts: "OVERWRITE"
  coredns:
    addon-version: v1.9.3-eksbuild.3
    resolve-conflicts: "OVERWRITE"

# key here is a mere human-readable description/tag
default-iam-policies: &default-iam-policies
  enable-ebs-creation: "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"

default-alb-dns-aliases: &alb-dns-aliases
  - api
  - auth-api

eks:
  cluster-module-source: cloudposse/eks-cluster/aws
  cluster-module-version: 2.6.0
  node-group-module-source: cloudposse/eks-node-group/aws
  node-group-module-version: 2.6.0
  regions:
    eu-west-1:
      cluster-name-0:
        alb-dns-aliases: *alb-dns-aliases
        k8s-version: 1.26
        network:
          vpc: exmaple-com
          subnet:
            name: pub
            kind: public
        addons:
          <<: *default-eks-addons
        helm-charts:
          <<: *default-helm-charts
        # FIXME: missing ec2 names while using managed node groups
        # https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2032  
        # potential fix: use our own launch templates
        node-groups:
          worker-group-0:
            desired-size: 1
            min-size: 1
            max-size: 3
            block-device-mappings:
              xvda:
                volume-size: 40 # gbs
                volume-type: gp3
                encrypted: false
                delete-on-termination: true
            autoscaler-enabled: true
            cluster-log-retention-period: 7
            instance-types: # if multiple are specified, the eks-node-group will randomly pick one
              - t3a.xlarge
            exposed-ports:
              <<: *default-exposed-ports
            extra-iam-policies:
              <<: *default-iam-policies
          non-exposed:
            desired-size: 1
            min-size: 1
            max-size: 3
            instance-types:
              - t3a.medium
              - t3a.xlarge
      cluster-name-1:
        alb-dns-aliases: *alb-dns-aliases
        k8s-version: 1.26
        vpc: exmaple-com
        subnet: pub
        addons:
          <<: *default-eks-addons
        helm-charts:
          <<: *default-helm-charts
        # FIXME: missing ec2 names while using managed node groups
        # https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2032  
        # potential fix: use our own launch templates
        node-groups:
          workers:
            desired-size: 1
            min-size: 1
            max-size: 10
            instance-types:
              - t3a.medium
            autoscaler-enabled: false
        
network:
  default_region: "eu-west-1"
  # NOTE: vpc names will be prefixed with env_short
  default_vpc: "exmaple-com"
  route53:
    zones:
      default:
        tld: "metadata.dev.cf-deployments.org"
  vpc:
    vpc-module-source: "cloudposse/vpc/aws"
    vpc-module-version: "2.0.0"
    subnet-module-source: "cloudposse/dynamic-subnets/aws"
    subnet-module-version: "2.1.0"
    regions:
      eu-west-1:
        exmaple-com:
          ipv4-cidr: 172.1.0.0/16
          subnets:
            pub:
              ipv4-cidr: 172.1.3.0/24
              private_subnets_enabled: false
              public_subnets_enabled: true
              igw: true
              ngw: true
              availability-zones:
              - eu-west-1a
              - eu-west-1b
              - eu-west-1c
